version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test-reporter-setup
          command: mkdir -p ./reports/junit/ && npm install jest-junit
  test:
    docker:
      - image: circleci/node:8
    steps:
      - run:
          name: linter
          command: ./node_modules/.bin/standard
      - run:
          name: test
          command: ./node_modules/.bin/jest tests --ci --testResultsProcessor="jest-junit" --runInBand
          environment:
            NODE_ENV: test
            JEST_JUNIT_OUTPUT: reports/junit/jest.xml
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit/


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
